.build_cache: &build_cache
  - key: cache-cargo-$CI_COMMIT_REF_SLUG
    policy: pull-push
    paths:
      # Cargo cache
      # See: https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
      - $CI_PROJECT_DIR/build/.cargo/.crates.toml
      - $CI_PROJECT_DIR/build/.cargo/.crates2.json
      - $CI_PROJECT_DIR/build/.cargo/bin/
      - $CI_PROJECT_DIR/build/.cargo/registry/index/
      - $CI_PROJECT_DIR/build/.cargo/registry/cache/
      - $CI_PROJECT_DIR/build/.cargo/git/db/
  - key: cache-gradle-$CI_COMMIT_REF_SLUG
    policy: pull-push
    paths:
      - $CI_PROJECT_DIR/build/.gradle/caches
      - $CI_PROJECT_DIR/build/gradle/cache

.compressed_artifact_output: &compressed_artifact_output
  artifacts:
    untracked: false
    when: always
    access: all
    expire_in: "30 days"
    paths:
      # Jobs must specify the IRONFOX_JOB_ARTIFACT_NAME variable
      - $CI_PROJECT_DIR/artifacts/$IRONFOX_JOB_ARTIFACT_NAME.tar.xz

default:
  cache: []

variables: &build_variables
  PRODUCTION_BRANCH: main
  IRONFOX_CI: 1
  IF_CI_NAME: "IronFox CI"
  IF_CI_USERNAME: "ironfox-ci"
  IF_CI_EMAIL: "ci@ironfoxoss.org"

stages:
  - build_fdroid
  - build_site
  - build_docker
  - build_ironfox
  - release

update-fdroid-repo:
  image: fedora:43
  stage: build_fdroid
  rules:
    - if: $CI_PROJECT_NAMESPACE != "ironfox-oss"
      when: never
    - if: $CI_COMMIT_TAG
  tags:
    - saas-linux-2xlarge-amd64
  variables:
    FDROID_REPO_PATH: ironfox-oss/fdroid
    FDROID_REPO_BRANCH: dev
    META_REPO_BRANCH: main
    META_DIR_PATH: "./fdroid/metadata"
    META_FILE_NAME: "org.ironfoxoss.ironfox.yml"
    REPO_DIR_PATH: "./fdroid/repo"
    <<: *build_variables
  before_script:
    - sudo dnf update -y --refresh
    - sudo dnf install -y bash curl git git-lfs jq make
    - git config --global user.email "${IF_CI_EMAIL}"
    - git config --global user.name "${IF_CI_NAME}"
    - git config --global url."https://${IF_CI_USERNAME}:${GITLAB_CI_PUSH_TOKEN}@gitlab.com/".insteadOf "https://gitlab.com/"
  script:
    - set -euo pipefail
    - echo 'Downloading dependencies...'
    - bash -x scripts/get_sources.sh python
    - bash -x scripts/get_sources.sh uv
    - bash -x scripts/get_sources.sh androguard
    - echo 'Updating F-Droid repo...'
    - bash scripts/ci-update-fdroid.sh

update-site-repo:
  image: fedora:43
  stage: build_site
  rules:
    - if: $CI_PROJECT_NAMESPACE != "ironfox-oss"
      when: never
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "dev"
      changes:
      - scripts/a-s-patches.yaml
      - scripts/glean-patches.yaml
      - scripts/patches.yaml
      - scripts/ci-update-site.sh
  tags:
    - saas-linux-2xlarge-amd64
  variables:
    TARGET_REPO_PATH: ironfox-oss/ironfoxoss.org
    TARGET_REPO_BRANCH: dev
    <<: *build_variables
  before_script:
    - sudo dnf update -y --refresh
    - sudo dnf install -y bash curl git make yq
    - git config --global user.email "${IF_CI_EMAIL}"
    - git config --global user.name "${IF_CI_NAME}"
    - git config --global url."https://${IF_CI_USERNAME}:${GITLAB_CI_PUSH_TOKEN}@gitlab.com/".insteadOf "https://gitlab.com/"
  script:
    - set -euo pipefail
    - echo 'Downloading dependencies...'
    - bash -x scripts/get_sources.sh python
    - bash -x scripts/get_sources.sh uv
    - bash -x scripts/get_sources.sh pyyaml
    - echo 'Updating website repo...'
    - bash scripts/ci-update-site.sh

build-docker:
  image: docker:cli
  stage: build_docker
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  script:
    - set -euo pipefail
    - docker build --pull -t "${DOCKER_IMAGE_NAME}" .
    - docker push "${DOCKER_IMAGE_NAME}"
    - |
      if [[ "${CI_COMMIT_BRANCH}" == "${CI_DEFAULT_BRANCH}" ]]; then
        docker tag "${DOCKER_IMAGE_NAME}" "${CI_REGISTRY_IMAGE}:latest"
        docker push "${CI_REGISTRY_IMAGE}:latest"
      fi
  rules:
    - if: $CI_PROJECT_NAMESPACE != "ironfox-oss"
      when: never
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
      changes:
        - Dockerfile
        - .gitlab-ci.yml
    - if: $CI_COMMIT_BRANCH == $PRODUCTION_BRANCH
  tags:
    - saas-linux-2xlarge-amd64

build-aar:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: build_ironfox
  timeout: 2h
  needs:
    - job: "build-docker"
      optional: true
  tags:
    - saas-linux-2xlarge-amd64
  parallel:
    matrix:
      - BUILD_VARIANT: ["arm", "arm64", "x86_64"]
  variables:
    RUNNER_SCRIPT_TIMEOUT: 8h
    IRONFOX_JOB_ARTIFACT_NAME: "build-aar-$BUILD_VARIANT"
    IRONFOX_ARTIFACT_INCLUDES: "aar;logs"
    <<: *build_variables
  script:
    - set -euo pipefail
    - echo 'Preparing secrets...'
    - bash scripts/ci-prep.sh sb
    - echo 'Building AAR...'
    - bash -x scripts/ci-build.sh "${BUILD_VARIANT}"
  <<: *compressed_artifact_output
  rules:
    - if: $CI_PROJECT_NAMESPACE != "ironfox-oss"
      when: never
    - changes:
        - patches/**/*
        - scripts/**/*
        - Dockerfile
        - .gitlab-ci.yml
    - if: $CI_COMMIT_TAG
      when: never

build-final:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: build_ironfox
  timeout: 6h
  needs:
    - job: "build-docker"
      optional: true
    - job: "build-aar"
      artifacts: true
      optional: false
  tags:
    - saas-linux-2xlarge-amd64
  variables:
    BUILD_VARIANT: "bundle"
    IRONFOX_JOB_ARTIFACT_NAME: "build-final-$BUILD_VARIANT"
    IRONFOX_ARTIFACT_INCLUDES: "apk;apks;logs"
    <<: *build_variables
  script:
    - set -euo pipefail
    - echo 'Preparing secrets...'
    - bash scripts/ci-prep.sh android-ks
    - bash scripts/ci-prep.sh sb
    - echo 'Building Bundle...'
    - bash -x scripts/ci-build.sh "${BUILD_VARIANT}"
  <<: *compressed_artifact_output
  rules:
    - if: $CI_PROJECT_NAMESPACE != "ironfox-oss"
      when: never
    - changes:
        - patches/**/*
        - scripts/**/*
        - Dockerfile
        - .gitlab-ci.yml
    - if: $CI_COMMIT_TAG
      when: never

prepare-release:
  image: fedora:43
  stage: release
  interruptible: true
  needs:
    - job: "build-docker"
      optional: true
    - job: "build-aar"
      artifacts: true
      optional: true
    - job: "build-final"
      artifacts: true
      optional: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $PRODUCTION_BRANCH && $CI_COMMIT_MESSAGE =~ /\[skip-release\]/
      when: never
    - if: $CI_COMMIT_BRANCH == $PRODUCTION_BRANCH
  tags:
    - saas-linux-2xlarge-amd64
  variables:
    <<: *build_variables
  before_script:
    - sudo dnf update -y --refresh
    - sudo dnf install -y curl jq
  script:
    - set -euo pipefail
    - echo 'Preparing secrets...'
    - bash scripts/ci-prep.sh s3
    - echo 'Downloading dependencies...'
    - bash -x scripts/get_sources.sh python
    - bash -x scripts/get_sources.sh uv
    - bash -x scripts/get_sources.sh s3cmd
    - echo 'Publishing packages...'
    - bash scripts/ci-publish-packages.sh
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: "30 days"
    paths:
      - build/release.yml

publish-release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  interruptible: true
  needs:
    - job: "prepare-release"
      artifacts: true
      optional: false
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $PRODUCTION_BRANCH && $CI_COMMIT_MESSAGE =~ /\[skip-release\]/
      when: never
    - if: $CI_COMMIT_BRANCH == $PRODUCTION_BRANCH
  tags:
    - saas-linux-2xlarge-amd64
  variables:
    <<: *build_variables
  script:
    - set -euo pipefail
    - |
      release-cli \
        --server-url "${CI_SERVER_URL}" \
        --project-id "${CI_PROJECT_ID}" \
        --private-token "${GITLAB_CI_API_TOKEN}" \
        create-from-file \
        --file build/release.yml
