# IronFox common environment variables

## CAUTION: Do NOT source this directly!
## Source 'env.sh' instead.

## Additionally, if you need to override any variables here, export them to your shell manually or use `env_override.sh`.
## Do NOT edit this file directly.

# If variables are defined with a custom `env_override.sh` file (located at the root project directory), let's use those
## These need to be set first, to ensure that they don't interfere with certain variables
IRONFOX_ENV_OVERRIDE="${IRONFOX_ROOT}/env_override.sh"
if [[ -f "${IRONFOX_ENV_OVERRIDE}" ]]; then
    source "${IRONFOX_ENV_OVERRIDE}"
fi

# IronFox

# Scripts directory
export IRONFOX_SCRIPTS="${IRONFOX_ROOT}/scripts"

# CI artifacts
export IRONFOX_ARTIFACTS="${IRONFOX_ROOT}/artifacts"
export IRONFOX_AAR_ARTIFACTS="${IRONFOX_ARTIFACTS}/aar"
export IRONFOX_APK_ARTIFACTS="${IRONFOX_ARTIFACTS}/apk"
export IRONFOX_APKS_ARTIFACTS="${IRONFOX_ARTIFACTS}/apks"
export IRONFOX_LOG_ARTIFACTS="${IRONFOX_ARTIFACTS}/logs"

# Are we in a CI environment?
IRONFOX_CI_DEFAULT=0
if [[ -z "${IRONFOX_CI+x}" ]]; then
    export IRONFOX_CI="${IRONFOX_CI_DEFAULT}"
fi

## If so, set our CI environment variables
IRONFOX_ENV_CI="${IRONFOX_SCRIPTS}/env_ci.sh"
if [ "${IRONFOX_CI}" == 1 ]; then
    source "${IRONFOX_ENV_CI}"
fi

# Environment configuration
export IRONFOX_ENV_FDROID="${IRONFOX_SCRIPTS}/env_fdroid.sh"

# Build environment configuration
export IRONFOX_ENV_BUILD="${IRONFOX_SCRIPTS}/env_build.sh"

# Build directory
export IRONFOX_BUILD="${IRONFOX_ROOT}/build"

# External sources directory
export IRONFOX_EXTERNAL="${IRONFOX_ROOT}/external"

# External downloads/resources directory
export IRONFOX_DOWNLOADS="${IRONFOX_EXTERNAL}/downloads"

# Patches directory
export IRONFOX_PATCHES="${IRONFOX_ROOT}/patches"

# Get our current commit
## (This is ex. displayed at `about:buildconfig` in Gecko/Firefox)
export IRONFOX_REVISION="$(git log -1 --format="%H" | tail -n 1)"

# Set our platform, OS, and architecture
export IRONFOX_ENV_HELPERS="${IRONFOX_SCRIPTS}/env_helpers.sh"
source "${IRONFOX_ENV_HELPERS}"

# Version info
export IRONFOX_VERSIONS="${IRONFOX_SCRIPTS}/versions.sh"

# IronFox outputs directory
IRONFOX_OUTPUTS_DEFAULT="${IRONFOX_BUILD}/outputs"
if [[ -z "${IRONFOX_OUTPUTS+x}" ]]; then
    export IRONFOX_OUTPUTS="${IRONFOX_OUTPUTS_DEFAULT}"
fi

# Whether we're building IronFox for release or Nightly/CI (Default)
IRONFOX_RELEASE_DEFAULT=0
if [[ -z "${IRONFOX_RELEASE+x}" ]]; then
    export IRONFOX_RELEASE="${IRONFOX_RELEASE_DEFAULT}"
fi

# Set release channel
if [[ "${IRONFOX_RELEASE}" == 1 ]]; then
    export IRONFOX_CHANNEL='release'
    export IRONFOX_CHANNEL_PRETTY='Release'
else
    export IRONFOX_CHANNEL='nightly'
    export IRONFOX_CHANNEL_PRETTY='Nightly'
fi

export IRONFOX_OUTPUTS_AAB="${IRONFOX_OUTPUTS}/aab"
export IRONFOX_OUTPUTS_AAR="${IRONFOX_OUTPUTS}/aar"
export IRONFOX_OUTPUTS_APK="${IRONFOX_OUTPUTS}/apk"
export IRONFOX_OUTPUTS_APKS="${IRONFOX_OUTPUTS}/apks"

export IRONFOX_OUTPUTS_GV_AAR_ARM="${IRONFOX_OUTPUTS_AAR}/geckoview-armeabi-v7a.zip"
export IRONFOX_OUTPUTS_GV_AAR_ARM64="${IRONFOX_OUTPUTS_AAR}/geckoview-arm64-v8a.zip"
export IRONFOX_OUTPUTS_GV_AAR_X86_64="${IRONFOX_OUTPUTS_AAR}/geckoview-x86_64.zip"

export IRONFOX_OUTPUTS_FENIX_ARM64_SIGNED="${IRONFOX_OUTPUTS_APK}/ironfox-${IRONFOX_CHANNEL}-arm64-v8a-signed.apk"
export IRONFOX_OUTPUTS_FENIX_ARM64_UNSIGNED="${IRONFOX_OUTPUTS_APK}/ironfox-${IRONFOX_CHANNEL}-arm64-v8a-unsigned.apk"
export IRONFOX_OUTPUTS_FENIX_ARM_SIGNED="${IRONFOX_OUTPUTS_APK}/ironfox-${IRONFOX_CHANNEL}-armeabi-v7a-signed.apk"
export IRONFOX_OUTPUTS_FENIX_ARM_UNSIGNED="${IRONFOX_OUTPUTS_APK}/ironfox-${IRONFOX_CHANNEL}-armeabi-v7a-unsigned.apk"
export IRONFOX_OUTPUTS_FENIX_X86_64_SIGNED="${IRONFOX_OUTPUTS_APK}/ironfox-${IRONFOX_CHANNEL}-x86_64-signed.apk"
export IRONFOX_OUTPUTS_FENIX_X86_64_UNSIGNED="${IRONFOX_OUTPUTS_APK}/ironfox-${IRONFOX_CHANNEL}-x86_64-unsigned.apk"
export IRONFOX_OUTPUTS_FENIX_UNIVERSAL_SIGNED="${IRONFOX_OUTPUTS_APK}/ironfox-${IRONFOX_CHANNEL}-universal-signed.apk"
export IRONFOX_OUTPUTS_FENIX_UNIVERSAL_UNSIGNED="${IRONFOX_OUTPUTS_APK}/ironfox-${IRONFOX_CHANNEL}-universal-unsigned.apk"
export IRONFOX_OUTPUTS_FENIX_AAB="${IRONFOX_OUTPUTS_AAB}/ironfox-${IRONFOX_CHANNEL}.aab"
export IRONFOX_OUTPUTS_FENIX_APKS="${IRONFOX_OUTPUTS_APKS}/ironfox-${IRONFOX_CHANNEL}.apks"

# Should we create a log file for build.sh? (Default)
IRONFOX_LOG_BUILD_DEFAULT=1
if [[ -z "${IRONFOX_LOG_BUILD+x}" ]]; then
    export IRONFOX_LOG_BUILD="${IRONFOX_LOG_BUILD_DEFAULT}"
fi

# Should we create a log file for prebuild.sh? (Default)
IRONFOX_LOG_PREBUILD_DEFAULT=1
if [[ -z "${IRONFOX_LOG_PREBUILD+x}" ]]; then
    export IRONFOX_LOG_PREBUILD="${IRONFOX_LOG_PREBUILD_DEFAULT}"
fi

# Should we create a log file for get_sources.sh? (Default)
IRONFOX_LOG_SOURCES_DEFAULT=1
if [[ -z "${IRONFOX_LOG_SOURCES+x}" ]]; then
    export IRONFOX_LOG_SOURCES="${IRONFOX_LOG_SOURCES_DEFAULT}"
fi

# Should we create a log file for sign.sh? (Default)
IRONFOX_LOG_SIGN_DEFAULT=1
if [[ -z "${IRONFOX_LOG_SIGN+x}" ]]; then
    export IRONFOX_LOG_SIGN="${IRONFOX_LOG_SIGN_DEFAULT}"
fi

# Directory where we should store log files (if logging is desired)
IRONFOX_LOG_DIR_DEFAULT="${IRONFOX_BUILD}/logs"
if [[ -z "${IRONFOX_LOG_DIR+x}" ]]; then
    export IRONFOX_LOG_DIR="${IRONFOX_LOG_DIR_DEFAULT}"
fi

# CI-specific build variables
# These variables are set for CI primarily to allow parallel builds (for specific stages)
IRONFOX_CI_BUILD_GECKO_ARM64_DEFAULT=0
if [[ -z "${IRONFOX_CI_BUILD_GECKO_ARM64+x}" ]]; then
    export IRONFOX_CI_BUILD_GECKO_ARM64="${IRONFOX_CI_BUILD_GECKO_ARM64_DEFAULT}"
fi

IRONFOX_CI_BUILD_GECKO_ARM_DEFAULT=0
if [[ -z "${IRONFOX_CI_BUILD_GECKO_ARM+x}" ]]; then
    export IRONFOX_CI_BUILD_GECKO_ARM="${IRONFOX_CI_BUILD_GECKO_ARM_DEFAULT}"
fi

IRONFOX_CI_BUILD_GECKO_X86_64_DEFAULT=0
if [[ -z "${IRONFOX_CI_BUILD_GECKO_X86_64+x}" ]]; then
    export IRONFOX_CI_BUILD_GECKO_X86_64="${IRONFOX_CI_BUILD_GECKO_X86_64_DEFAULT}"
fi

IRONFOX_CI_BUILD_FINAL_DEFAULT=0
if [[ -z "${IRONFOX_CI_BUILD_FINAL+x}" ]]; then
    export IRONFOX_CI_BUILD_FINAL="${IRONFOX_CI_BUILD_FINAL_DEFAULT}"
fi

# Android NDK
IRONFOX_ANDROID_NDK_DEFAULT="${IRONFOX_EXTERNAL}/android-ndk"
if [[ -z "${IRONFOX_ANDROID_NDK+x}" ]]; then
    export IRONFOX_ANDROID_NDK="${IRONFOX_ANDROID_NDK_DEFAULT}"
fi

# Android SDK
IRONFOX_ANDROID_SDK_DEFAULT="${IRONFOX_EXTERNAL}/android-sdk"
if [[ -z "${IRONFOX_ANDROID_SDK+x}" ]]; then
    export IRONFOX_ANDROID_SDK="${IRONFOX_ANDROID_SDK_DEFAULT}"
fi

## sdkmanager
export IRONFOX_ANDROID_SDKMANAGER="${IRONFOX_ANDROID_SDK}/cmdline-tools/latest/bin/sdkmanager"

# Android SDK Build Tools (Latest)
IRONFOX_ANDROID_SDK_BUILD_TOOLS_DEFAULT="${IRONFOX_EXTERNAL}/android-sdk-build-tools"
if [[ -z "${IRONFOX_ANDROID_SDK_BUILD_TOOLS+x}" ]]; then
    export IRONFOX_ANDROID_SDK_BUILD_TOOLS="${IRONFOX_ANDROID_SDK_BUILD_TOOLS_DEFAULT}"
fi

## apksigner
IRONFOX_APKSIGNER_DEFAULT="${IRONFOX_ANDROID_SDK_BUILD_TOOLS}/apksigner"
if [[ -z "${IRONFOX_APKSIGNER+x}" ]]; then
    export IRONFOX_APKSIGNER="${IRONFOX_APKSIGNER_DEFAULT}"
fi

# Android SDK Build Tools (35 - needed by Glean)
IRONFOX_ANDROID_SDK_BUILD_TOOLS_35_DEFAULT="${IRONFOX_EXTERNAL}/android-sdk-build-tools-35"
if [[ -z "${IRONFOX_ANDROID_SDK_BUILD_TOOLS_35+x}" ]]; then
    export IRONFOX_ANDROID_SDK_BUILD_TOOLS_35="${IRONFOX_ANDROID_SDK_BUILD_TOOLS_35_DEFAULT}"
fi

# Android SDK Platform Tools
IRONFOX_ANDROID_SDK_PLATFORM_TOOLS_DEFAULT="${IRONFOX_EXTERNAL}/android-sdk-platform-tools"
if [[ -z "${IRONFOX_ANDROID_SDK_PLATFORM_TOOLS+x}" ]]; then
    export IRONFOX_ANDROID_SDK_PLATFORM_TOOLS="${IRONFOX_ANDROID_SDK_PLATFORM_TOOLS_DEFAULT}"
fi

## ADB
IRONFOX_ADB_DEFAULT="${IRONFOX_ANDROID_SDK_PLATFORM_TOOLS}/adb"
if [[ -z "${IRONFOX_ADB+x}" ]]; then
    export IRONFOX_ADB="${IRONFOX_ADB_DEFAULT}"
fi

# Application Services
IRONFOX_AS_DEFAULT="${IRONFOX_EXTERNAL}/application-services"
if [[ -z "${IRONFOX_AS+x}" ]]; then
    export IRONFOX_AS="${IRONFOX_AS_DEFAULT}"
fi

## Application Services overlay
export IRONFOX_AS_OVERLAY="${IRONFOX_PATCHES}/a-s-overlay"

# Bundletool
IRONFOX_BUNDLETOOL_DIR_DEFAULT="${IRONFOX_EXTERNAL}/bundletool"
if [[ -z "${IRONFOX_BUNDLETOOl_DIR+x}" ]]; then
    export IRONFOX_BUNDLETOOL_DIR="${IRONFOX_BUNDLETOOL_DIR_DEFAULT}"
fi
export IRONFOX_BUNDLETOOL="${IRONFOX_BUNDLETOOL_DIR}/bundletool"
export IRONFOX_BUNDLETOOL_JAR="${IRONFOX_BUNDLETOOL_DIR}/bundletool.jar"

# cbindgen
IRONFOX_CBINDGEN_DEFAULT="${IRONFOX_EXTERNAL}/cbindgen"
if [[ -z "${IRONFOX_CBINDGEN+x}" ]]; then
    export IRONFOX_CBINDGEN="${IRONFOX_CBINDGEN_DEFAULT}"
fi

# Firefox (mozilla-central)
IRONFOX_GECKO_DEFAULT="${IRONFOX_EXTERNAL}/gecko"
if [[ -z "${IRONFOX_GECKO+x}" ]]; then
    export IRONFOX_GECKO="${IRONFOX_GECKO_DEFAULT}"
fi

## mach
export IRONFOX_MACH="${IRONFOX_GECKO}/mach"

## Gecko overlay
export IRONFOX_GECKO_OVERLAY="${IRONFOX_PATCHES}/gecko-overlay"

## Android Components
export IRONFOX_AC="${IRONFOX_GECKO}/mobile/android/android-components"

### Android Components overlay
export IRONFOX_AC_OVERLAY="${IRONFOX_PATCHES}/a-c-overlay"

## Fenix
export IRONFOX_FENIX="${IRONFOX_GECKO}/mobile/android/fenix"

### Fenix overlay
export IRONFOX_FENIX_OVERLAY="${IRONFOX_PATCHES}/fenix-overlay"

## Gecko locales
IRONFOX_GECKO_LOCALES_DEFAULT=$(<"${IRONFOX_PATCHES}/locales")
if [[ -z "${IRONFOX_GECKO_LOCALES+x}" ]]; then
    export IRONFOX_GECKO_LOCALES="${IRONFOX_GECKO_LOCALES_DEFAULT}"
fi

## Gecko l10n
IRONFOX_L10N_CENTRAL_DEFAULT="${IRONFOX_EXTERNAL}/l10n-central"
if [[ -z "${IRONFOX_L10N_CENTRAL+x}" ]]; then
    export IRONFOX_L10N_CENTRAL="${IRONFOX_L10N_CENTRAL_DEFAULT}"
fi

## .mozbuild
IRONFOX_MOZBUILD_DEFAULT="${IRONFOX_BUILD}/.mozbuild"
if [[ -z "${IRONFOX_MOZBUILD+x}" ]]; then
    export IRONFOX_MOZBUILD="${IRONFOX_MOZBUILD_DEFAULT}"
fi

# Glean
IRONFOX_GLEAN_DEFAULT="${IRONFOX_EXTERNAL}/glean"
if [[ -z "${IRONFOX_GLEAN+x}" ]]; then
    export IRONFOX_GLEAN="${IRONFOX_GLEAN_DEFAULT}"
fi

## Glean overlay
export IRONFOX_GLEAN_OVERLAY="${IRONFOX_PATCHES}/glean-overlay"

# Glean Parser wheels
IRONFOX_GLEAN_PARSER_WHEELS_DEFAULT="${IRONFOX_EXTERNAL}/glean_parser-wheels"
if [[ -z "${IRONFOX_GLEAN_PARSER_WHEELS+x}" ]]; then
    export IRONFOX_GLEAN_PARSER_WHEELS="${IRONFOX_GLEAN_PARSER_WHEELS_DEFAULT}"
fi

# GNU awk
if [[ "${IRONFOX_OS}" == 'osx' ]]; then
    IRONFOX_AWK_DEFAULT='gawk'
else
    IRONFOX_AWK_DEFAULT='awk'
fi
if [[ -z "${IRONFOX_AWK+x}" ]]; then
    export IRONFOX_AWK="${IRONFOX_AWK_DEFAULT}"
fi

# GNU date
if [[ "${IRONFOX_OS}" == 'osx' ]]; then
    IRONFOX_DATE_DEFAULT='gdate'
else
    IRONFOX_DATE_DEFAULT='date'
fi
if [[ -z "${IRONFOX_DATE+x}" ]]; then
    export IRONFOX_DATE="${IRONFOX_DATE_DEFAULT}"
fi

# GNU make
if [[ "${IRONFOX_OS}" == 'osx' ]]; then
    IRONFOX_MAKE_DEFAULT='gmake'
else
    IRONFOX_MAKE_DEFAULT='make'
fi
if [[ -z "${IRONFOX_MAKE+x}" ]]; then
    export IRONFOX_MAKE="${IRONFOX_MAKE_DEFAULT}"
fi

# GNU sed
if [[ "${IRONFOX_OS}" == 'osx' ]]; then
    IRONFOX_SED_DEFAULT='gsed'
else
    IRONFOX_SED_DEFAULT='sed'
fi
if [[ -z "${IRONFOX_SED+x}" ]]; then
    export IRONFOX_SED="${IRONFOX_SED_DEFAULT}"
fi

# GNU tar
if [[ "${IRONFOX_OS}" == 'osx' ]]; then
    IRONFOX_TAR_DEFAULT='gtar'
else
    IRONFOX_TAR_DEFAULT='tar'
fi
if [[ -z "${IRONFOX_TAR+x}" ]]; then
    export IRONFOX_TAR="${IRONFOX_TAR_DEFAULT}"
fi

# Gradle
IRONFOX_GRADLE_DIR_DEFAULT="${IRONFOX_EXTERNAL}/gradle"
if [[ -z "${IRONFOX_GRADLE_DIR+x}" ]]; then
    export IRONFOX_GRADLE_DIR="${IRONFOX_GRADLE_DIR_DEFAULT}"
fi
export IRONFOX_GRADLE="${IRONFOX_GRADLE_DIR}/gradle"

## Gradle cache
IRONFOX_GRADLE_CACHE_DEFAULT="${IRONFOX_BUILD}/gradle/cache"
if [[ -z "${IRONFOX_GRADLE_CACHE+x}" ]]; then
    export IRONFOX_GRADLE_CACHE="${IRONFOX_GRADLE_CACHE_DEFAULT}"
fi

## Gradle home
IRONFOX_GRADLE_HOME_DEFAULT="${IRONFOX_BUILD}/.gradle"
if [[ -z "${IRONFOX_GRADLE_HOME+x}" ]]; then
    export IRONFOX_GRADLE_HOME="${IRONFOX_GRADLE_HOME_DEFAULT}"
fi

# Gradle local Maven repository
IRONFOX_MAVEN_LOCAL_DEFAULT="${IRONFOX_BUILD}/.m2/repository"
if [[ -z "${IRONFOX_MAVEN_LOCAL+x}" ]]; then
    export IRONFOX_MAVEN_LOCAL="${IRONFOX_MAVEN_LOCAL_DEFAULT}"
fi

# GYP
IRONFOX_GYP_DEFAULT="${IRONFOX_EXTERNAL}/gyp-next"
if [[ -z "${IRONFOX_GYP+x}" ]]; then
    export IRONFOX_GYP="${IRONFOX_GYP_DEFAULT}"
fi

# Java home
if [[ "${IRONFOX_OS}" == 'osx' ]]; then
    IRONFOX_JAVA_HOME_DEFAULT='/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home'
else
    IRONFOX_JAVA_HOME_DEFAULT='/usr/lib/jvm/temurin-17-jdk'
fi
if [[ -z "${IRONFOX_JAVA_HOME+x}" ]]; then
    export IRONFOX_JAVA_HOME="${IRONFOX_JAVA_HOME_DEFAULT}"
fi

# libclang
if [[ "${IRONFOX_OS}" == 'osx' ]]; then
    IRONFOX_LIBCLANG_DEFAULT="${IRONFOX_ANDROID_NDK}/toolchains/llvm/prebuilt/${IRONFOX_PLATFORM}-x86_64/lib"
else
    IRONFOX_LIBCLANG_DEFAULT="${IRONFOX_ANDROID_NDK}/toolchains/llvm/prebuilt/${IRONFOX_PLATFORM}-x86_64/musl/lib"
fi
if [[ -z "${IRONFOX_LIBCLANG+x}" ]]; then
    export IRONFOX_LIBCLANG="${IRONFOX_LIBCLANG_DEFAULT}"
fi

# llvm-profdata
IRONFOX_LLVM_PROFDATA_DEFAULT="${IRONFOX_ANDROID_NDK}/toolchains/llvm/prebuilt/${IRONFOX_PLATFORM}-x86_64/bin/llvm-profdata"
if [[ -z "${IRONFOX_LLVM_PROFDATA+x}" ]]; then
    export IRONFOX_LLVM_PROFDATA="${IRONFOX_LLVM_PROFDATA_DEFAULT}"
fi

# microG
IRONFOX_GMSCORE_DEFAULT="${IRONFOX_EXTERNAL}/gmscore"
if [[ -z "${IRONFOX_GMSCORE+x}" ]]; then
    export IRONFOX_GMSCORE="${IRONFOX_GMSCORE_DEFAULT}"
fi

# nproc
if [[ "${IRONFOX_OS}" == 'osx' ]]; then
    IRONFOX_NPROC_DEFAULT='sysctl -n hw.logicalcpu'
else
    IRONFOX_NPROC_DEFAULT='nproc'
fi
if [[ -z "${IRONFOX_NPROC+x}" ]]; then
    export IRONFOX_NPROC="${IRONFOX_NPROC_DEFAULT}"
fi

# NSS
IRONFOX_NSS_DIR_DEFAULT="${IRONFOX_AS}/libs/desktop/${IRONFOX_PLATFORM}-${IRONFOX_PLATFORM_ARCH}/nss"
if [[ -z "${IRONFOX_NSS_DIR+x}" ]]; then
    export IRONFOX_NSS_DIR="${IRONFOX_NSS_DIR_DEFAULT}"
fi

# IronFox prebuilds
IRONFOX_PREBUILDS_DEFAULT="${IRONFOX_EXTERNAL}/prebuilds"
if [[ -z "${IRONFOX_PREBUILDS+x}" ]]; then
    export IRONFOX_PREBUILDS="${IRONFOX_PREBUILDS_DEFAULT}"
fi

# Phoenix
IRONFOX_PHOENIX_DEFAULT="${IRONFOX_EXTERNAL}/phoenix"
if [[ -z "${IRONFOX_PHOENIX+x}" ]]; then
    export IRONFOX_PHOENIX="${IRONFOX_PHOENIX_DEFAULT}"
fi

# pip
IRONFOX_PIP_DEFAULT="${IRONFOX_EXTERNAL}/pip"
if [[ -z "${IRONFOX_PIP+x}" ]]; then
    export IRONFOX_PIP="${IRONFOX_PIP_DEFAULT}"
fi

# Python (Glean)
export IRONFOX_GLEAN_PIP_ENV="${IRONFOX_GRADLE_HOME}/glean"

# Python (pip) environment
IRONFOX_PIP_DIR_DEFAULT="${IRONFOX_BUILD}/pyenv"
if [[ -z "${IRONFOX_PIP_DIR+x}" ]]; then
    export IRONFOX_PIP_DIR="${IRONFOX_PIP_DIR_DEFAULT}"
fi
export IRONFOX_PIP_ENV="${IRONFOX_PIP_DIR}/bin/activate"

## For macOS, ensure that Python 3.9 is in PATH
if [[ "${IRONFOX_OS}" == 'osx' ]]; then
    export PATH="${PATH}:$(brew --prefix)/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin"
fi

# Rust (cargo)
IRONFOX_CARGO_HOME_DEFAULT="${IRONFOX_BUILD}/.cargo"
if [[ -z "${IRONFOX_CARGO_HOME+x}" ]]; then
    export IRONFOX_CARGO_HOME="${IRONFOX_CARGO_HOME_DEFAULT}"
fi
export IRONFOX_CARGO="${IRONFOX_CARGO_HOME}/bin/cargo"
export IRONFOX_CARGO_ENV="${IRONFOX_CARGO_HOME}/env"
export IRONFOX_RUSTC="${IRONFOX_CARGO_HOME}/bin/rustc"
export IRONFOX_RUSTDOC="${IRONFOX_CARGO_HOME}/bin/rustdoc"

## Display progress bars
IRONFOX_CARGO_PROGRESS_BAR_DEFAULT='always'
if [[ -z "${IRONFOX_CARGO_PROGRESS_BAR+x}" ]]; then
    export IRONFOX_CARGO_PROGRESS_BAR="${IRONFOX_CARGO_PROGRESS_BAR_DEFAULT}"
fi

## Enable colored output
IRONFOX_CARGO_COLORED_OUTPUT_DEFAULT='always'
if [[ -z "${IRONFOX_CARGO_COLORED_OUTPUT+x}" ]]; then
    export IRONFOX_CARGO_COLORED_OUTPUT="${IRONFOX_CARGO_COLORED_OUTPUT_DEFAULT}"
fi

# rustup
IRONFOX_RUSTUP_HOME_DEFAULT="${IRONFOX_BUILD}/.rustup"
if [[ -z "${IRONFOX_RUSTUP_HOME+x}" ]]; then
    export IRONFOX_RUSTUP_HOME="${IRONFOX_RUSTUP_HOME_DEFAULT}"
fi

## Display progress bars
IRONFOX_RUSTUP_PROGRESS_BAR_DEFAULT='always'
if [[ -z "${IRONFOX_RUSTUP_PROGRESS_BAR+x}" ]]; then
    export IRONFOX_RUSTUP_PROGRESS_BAR="${IRONFOX_RUSTUP_PROGRESS_BAR_DEFAULT}"
fi

## Enable colored output
IRONFOX_RUSTUP_COLORED_OUTPUT_DEFAULT='always'
if [[ -z "${IRONFOX_RUSTUP_COLORED_OUTPUT+x}" ]]; then
    export IRONFOX_RUSTUP_COLORED_OUTPUT="${IRONFOX_RUSTUP_COLORED_OUTPUT_DEFAULT}"
fi

# uniffi-bindgen
IRONFOX_UNIFFI_DEFAULT="${IRONFOX_EXTERNAL}/uniffi"
if [[ -z "${IRONFOX_UNIFFI+x}" ]]; then
    export IRONFOX_UNIFFI="${IRONFOX_UNIFFI_DEFAULT}"
fi

# unifiedpush-ac
IRONFOX_UP_AC_DEFAULT="${IRONFOX_EXTERNAL}/unifiedpush-ac"
if [[ -z "${IRONFOX_UP_AC+x}" ]]; then
    export IRONFOX_UP_AC="${IRONFOX_UP_AC_DEFAULT}"
fi

# WASI SDK
IRONFOX_WASI_DEFAULT="${IRONFOX_EXTERNAL}/wasi-sdk"
if [[ -z "${IRONFOX_WASI+x}" ]]; then
    export IRONFOX_WASI="${IRONFOX_WASI_DEFAULT}"
fi

# If compiler flags are added, this determines whether they should be appended to our default flags (default),
## or if they should override them entirely
IRONFOX_COMPILER_FLAGS_OVERRIDE_DEFAULT=0
if [[ -z "${IRONFOX_COMPILER_FLAGS_OVERRIDE+x}" ]]; then
    export IRONFOX_COMPILER_FLAGS_OVERRIDE="${IRONFOX_COMPILER_FLAGS_OVERRIDE_DEFAULT}"
fi

# Compiler flags
IRONFOX_COMPILER_FLAGS_DEFAULT='-DNDEBUG -O3 -fstack-clash-protection -fstack-protector-strong -ftrivial-auto-var-init=zero -fwrapv'
if [[ -z "${IRONFOX_COMPILER_FLAGS+x}" ]]; then
    export IRONFOX_COMPILER_FLAGS_OVERRIDE=1
    export IRONFOX_COMPILER_FLAGS="${IRONFOX_COMPILER_FLAGS_DEFAULT}"
elif [[ "${IRONFOX_COMPILER_FLAGS_OVERRIDE}" == 1 ]]; then
    export IRONFOX_COMPILER_FLAGS="${IRONFOX_COMPILER_FLAGS}"
else
    export IRONFOX_COMPILER_FLAGS="${IRONFOX_COMPILER_FLAGS_DEFAULT} ${IRONFOX_COMPILER_FLAGS}"
fi

# If curl flags are added, this determines whether they should be appended to our default flags (default),
## or if they should override them entirely
IRONFOX_CURL_FLAGS_OVERRIDE_DEFAULT=0
if [[ -z "${IRONFOX_CURL_FLAGS_OVERRIDE+x}" ]]; then
    export IRONFOX_CURL_FLAGS_OVERRIDE="${IRONFOX_CURL_FLAGS_OVERRIDE_DEFAULT}"
fi

# curl flags
IRONFOX_CURL_FLAGS_DEFAULT='-q --disable --no-netrc -j -e "" -A "" -S --clobber --create-dirs --delegation none --disallow-username-in-url --doh-cert-status --ftp-create-dirs --ftp-ssl-control --junk-session-cookies --no-basic --no-ca-native --no-digest --no-doh-insecure --no-http0.9 --no-insecure --no-proxy-insecure --no-negotiate --no-ntlm --no-proxy-basic --no-proxy-ca-native --no-proxy-digest --no-proxy-insecure --no-proxy-ntlm --no-proxy-ssl-allow-beast --no-proxy-ssl-auto-client-cert --no-sessionid --no-skip-existing --no-ssl --no-ssl-allow-beast --no-ssl-auto-client-cert --no-ssl-no-revoke --no-ssl-revoke-best-effort --no-tls-earlydata --no-xattr --progress-meter --proto -all,https --proto-default https --proto-redir -all,https --referer "" --remove-on-error --show-error --ssl-reqd --trace-time --user-agent "" --verbose'
if [[ -z "${IRONFOX_CURL_FLAGS+x}" ]]; then
    export IRONFOX_CURL_FLAGS_OVERRIDE=1
    export IRONFOX_CURL_FLAGS="${IRONFOX_CURL_FLAGS_DEFAULT}"
elif [[ "${IRONFOX_CURL_FLAGS_OVERRIDE}" == 1 ]]; then
    export IRONFOX_CURL_FLAGS="${IRONFOX_CURL_FLAGS}"
else
    export IRONFOX_CURL_FLAGS="${IRONFOX_CURL_FLAGS_DEFAULT} ${IRONFOX_CURL_FLAGS}"
fi

# If Gradle flags are added, this determines whether they should be appended to our default flags (default),
## or if they should override them entirely
IRONFOX_GRADLE_FLAGS_OVERRIDE_DEFAULT=0
if [[ -z "${IRONFOX_GRADLE_FLAGS_OVERRIDE+x}" ]]; then
    export IRONFOX_GRADLE_FLAGS_OVERRIDE="${IRONFOX_GRADLE_FLAGS_OVERRIDE_DEFAULT}"
fi

# Gradle flags
IRONFOX_GRADLE_FLAGS_DEFAULT="-Dmaven.repo.local=${IRONFOX_MAVEN_LOCAL} -Dorg.gradle.caching=false -Dorg.gradle.configuration-cache=false -Dorg.gradle.daemon=false -Dorg.gradle.debug=false --no-build-cache --no-configuration-cache --no-daemon"
if [[ -z "${IRONFOX_GRADLE_FLAGS+x}" ]]; then
    export IRONFOX_GRADLE_FLAGS_OVERRIDE=1
    export IRONFOX_GRADLE_FLAGS="${IRONFOX_GRADLE_FLAGS_DEFAULT}"
elif [[ "${IRONFOX_GRADLE_FLAGS_OVERRIDE}" == 1 ]]; then
    export IRONFOX_GRADLE_FLAGS="${IRONFOX_GRADLE_FLAGS}"
else
    export IRONFOX_GRADLE_FLAGS="${IRONFOX_GRADLE_FLAGS_DEFAULT} ${IRONFOX_GRADLE_FLAGS}"
fi

# If Rust flags are added, this determines whether they should be appended to our default flags (default),
## or if they should override them entirely
IRONFOX_RUST_FLAGS_OVERRIDE_DEFAULT=0
if [[ -z "${IRONFOX_RUST_FLAGS_OVERRIDE+x}" ]]; then
    export IRONFOX_RUST_FLAGS_OVERRIDE="${IRONFOX_RUST_FLAGS_OVERRIDE_DEFAULT}"
fi

# Rust flags
IRONFOX_RUST_FLAGS_DEFAULT='-Ccontrol-flow-guard=true -Cdebug-assertions=false -Cdebuginfo=0 -Clink-dead-code=false -Copt-level=3 -Coverflow-checks=true -Cstrip=debuginfo -O'
if [[ -z "${IRONFOX_RUST_FLAGS+x}" ]]; then
    export IRONFOX_RUST_FLAGS_OVERRIDE=1
    export IRONFOX_RUST_FLAGS="${IRONFOX_RUST_FLAGS_DEFAULT}"
elif [[ "${IRONFOX_RUST_FLAGS_OVERRIDE}" == 1 ]]; then
    export IRONFOX_RUST_FLAGS="${IRONFOX_RUST_FLAGS}"
else
    export IRONFOX_RUST_FLAGS="${IRONFOX_RUST_FLAGS_DEFAULT} ${IRONFOX_RUST_FLAGS}"
fi

# Whether we should use our prebuilt libraries (Default)
## (This is currently uniffi-bindgen and WASI SDK for us)
IRONFOX_NO_PREBUILDS_DEFAULT=0
if [[ -z "${IRONFOX_NO_PREBUILDS+x}" ]]; then
    export IRONFOX_NO_PREBUILDS="${IRONFOX_NO_PREBUILDS_DEFAULT}"
fi

# Location to the Google Safe Browsing API keyfile (if Safe Browsing is desired)
IRONFOX_SB_GAPI_KEY_FILE_DEFAULT='null'
if [[ -z "${IRONFOX_SB_GAPI_KEY_FILE+x}" ]]; then
    export IRONFOX_SB_GAPI_KEY_FILE="${IRONFOX_SB_GAPI_KEY_FILE_DEFAULT}"
fi

# Do we want Mach to actually build *something*? (Default)
## This will generally always be true, but we want to disable it for ex. packaging
IRONFOX_MACH_BUILD_DEFAULT=1
if [[ -z "${IRONFOX_MACH_BUILD+x}" ]]; then
    export IRONFOX_MACH_BUILD="${IRONFOX_MACH_BUILD_DEFAULT}"
fi

# Should Mach target Android Components?
IRONFOX_MACH_TARGET_AC_DEFAULT=0
if [[ -z "${IRONFOX_MACH_TARGET_AC+x}" ]]; then
    export IRONFOX_MACH_TARGET_AC="${IRONFOX_MACH_TARGET_AC_DEFAULT}"
fi

# Should Mach target Fenix?
IRONFOX_MACH_TARGET_FENIX_DEFAULT=0
if [[ -z "${IRONFOX_MACH_TARGET_FENIX+x}" ]]; then
    export IRONFOX_MACH_TARGET_FENIX="${IRONFOX_MACH_TARGET_FENIX_DEFAULT}"
fi

# Should Mach target Gecko(View)?
IRONFOX_MACH_TARGET_GECKO_DEFAULT=0
if [[ -z "${IRONFOX_MACH_TARGET_GECKO+x}" ]]; then
    export IRONFOX_MACH_TARGET_GECKO="${IRONFOX_MACH_TARGET_GECKO_DEFAULT}"
fi

# Should Mach target ARM64 (GeckoView AAR) if we're creating a bundle?
IRONFOX_MACH_TARGET_BUNDLE_ARM64_DEFAULT=0
if [[ -z "${IRONFOX_MACH_TARGET_BUNDLE_ARM64+x}" ]]; then
    export IRONFOX_MACH_TARGET_BUNDLE_ARM64="${IRONFOX_MACH_TARGET_BUNDLE_ARM64_DEFAULT}"
fi

# Should Mach target ARM (GeckoView AAR) if we're creating a bundle?
IRONFOX_MACH_TARGET_BUNDLE_ARM_DEFAULT=0
if [[ -z "${IRONFOX_MACH_TARGET_BUNDLE_ARM+x}" ]]; then
    export IRONFOX_MACH_TARGET_BUNDLE_ARM="$IRONFOX_MACH_TARGET_BUNDLE_ARM_DEFAULT}"
fi

# Should Mach target x86_64 (GeckoView AAR) if we're creating a bundle?
IRONFOX_MACH_TARGET_BUNDLE_X86_64_DEFAULT=0
if [[ -z "${IRONFOX_MACH_TARGET_BUNDLE_X86_64+x}" ]]; then
    export IRONFOX_MACH_TARGET_BUNDLE_X86_64="${IRONFOX_MACH_TARGET_BUNDLE_X86_64_DEFAULT}"
fi

# App signing

# Location to the Android keystore file that we should use
IRONFOX_KEYSTORE_DEFAULT='null'
if [[ -z "${IRONFOX_KEYSTORE+x}" ]]; then
    export IRONFOX_KEYSTORE="${IRONFOX_KEYSTORE_DEFAULT}"
fi

# Location to the Android keystore pass file that we should use
IRONFOX_KEYSTORE_PASS_FILE_DEFAULT='null'
if [[ -z "${IRONFOX_KEYSTORE_PASS_FILE+x}" ]]; then
    export IRONFOX_KEYSTORE_PASS_FILE="${IRONFOX_KEYSTORE_PASS_FILE_DEFAULT}"
fi

# Alias of the Android keystore that we should use
IRONFOX_KEYSTORE_KEY_ALIAS_DEFAULT='null'
if [[ -z "${IRONFOX_KEYSTORE_KEY_ALIAS+x}" ]]; then
    export IRONFOX_KEYSTORE_KEY_ALIAS="${IRONFOX_KEYSTORE_KEY_ALIAS_DEFAULT}"
fi

# Location to the Android keystore key pass file that we should use
IRONFOX_KEYSTORE_KEY_PASS_FILE_DEFAULT='null'
if [[ -z "${IRONFOX_KEYSTORE_KEY_PASS_FILE+x}" ]]; then
    export IRONFOX_KEYSTORE_KEY_PASS_FILE="${IRONFOX_KEYSTORE_KEY_PASS_FILE_DEFAULT}"
fi

# Should we automatically sign our output APK(S) files?
IRONFOX_SIGN_DEFAULT=0
if [ "${IRONFOX_KEYSTORE}" != 'null' ] && [ "${IRONFOX_KEYSTORE_PASS_FILE}" != 'null' ] && [ "${IRONFOX_KEYSTORE_KEY_ALIAS}" != 'null' ] && [ "${IRONFOX_KEYSTORE_KEY_PASS_FILE}" != 'null' ]; then
    export IRONFOX_SIGN=1
else
    export IRONFOX_SIGN="${IRONFOX_SIGN_DEFAULT}"
fi

# Locations for our GeckoView AAR archives

## Where our GeckoView ARM64 AAR archive is located within mozilla-central
IRONFOX_GV_AAR_ARM64_DEFAULT="${IRONFOX_GECKO}/obj/ironfox-${IRONFOX_CHANNEL}-arm64/gradle/target.maven.zip"
if [[ -z "${IRONFOX_GV_AAR_ARM64+x}" ]]; then
    export IRONFOX_GV_AAR_ARM64="${IRONFOX_GV_AAR_ARM64_DEFAULT}"
fi

## Where our GeckoView ARM AAR archive is located within mozilla-central
IRONFOX_GV_AAR_ARM_DEFAULT="${IRONFOX_GECKO}/obj/ironfox-${IRONFOX_CHANNEL}-arm/gradle/target.maven.zip"
if [[ -z "${IRONFOX_GV_AAR_ARM+x}" ]]; then
    export IRONFOX_GV_AAR_ARM="${IRONFOX_GV_AAR_ARM_DEFAULT}"
fi

## Where our GeckoView x86_64 AAR archive is located within mozilla-central
IRONFOX_GV_AAR_X86_64_DEFAULT="${IRONFOX_GECKO}/obj/ironfox-${IRONFOX_CHANNEL}-x86_64/gradle/target.maven.zip"
if [[ -z "${IRONFOX_GV_AAR_X86_64+x}" ]]; then
    export IRONFOX_GV_AAR_X86_64="${IRONFOX_GV_AAR_X86_64_DEFAULT}"
fi

# Set our external environment variables
IRONFOX_ENV_EXTERNAL="${IRONFOX_SCRIPTS}/env_external.sh"
source "${IRONFOX_ENV_EXTERNAL}"
