#!/bin/bash

source "$rootdir/scripts/versions.sh"

if [[ "$env_source" != "true" ]]; then
    echo "Use 'source scripts/env_local.sh' before calling prebuild or build"
    return 1
fi

function noop_mozilla_endpoints() {
    local endpoint="$1"
    local dir="$2"

    # Find files containing the endpoint
    local files=$(grep -rnlI --exclude=*.json --exclude=*.md --exclude=*.swift --exclude-dir=androidTest --exclude-dir=docs --exclude-dir=test --exclude-dir=tests "${dir}" -e "\"${endpoint}[^\"']*\"" -e "'${endpoint}[^\"']*'")
    local files_slash=$(grep -rnlI --exclude=*.json --exclude=*.md --exclude=*.swift --exclude-dir=androidTest --exclude-dir=docs --exclude-dir=test --exclude-dir=tests "${dir}" -e "\"${endpoint}/[^\"']*\"" -e "'${endpoint}/[^\"']*'")
    local files_period=$(grep -rnlI --exclude=*.json --exclude=*.md --exclude=*.swift --exclude-dir=androidTest --exclude-dir=docs --exclude-dir=test --exclude-dir=tests "${dir}" -e "\"${endpoint}.[^\"']*\"" -e "'${endpoint}.[^\"']*'")
    local http_files=$(grep -rnlI --exclude=*.json --exclude=*.md --exclude=*.swift --exclude-dir=androidTest --exclude-dir=docs --exclude-dir=test --exclude-dir=tests "${dir}" -e "\"http://${endpoint}[^\"']*\"" -e "'http://${endpoint}[^\"']*'")
    local http_files_slash=$(grep -rnlI --exclude=*.json --exclude=*.md --exclude=*.swift --exclude-dir=androidTest --exclude-dir=docs --exclude-dir=test --exclude-dir=tests "${dir}" -e "\"http://${endpoint}/[^\"']*\"" -e "'http://${endpoint}/[^\"']*'")
    local http_files_period=$(grep -rnlI --exclude=*.json --exclude=*.md --exclude=*.swift --exclude-dir=androidTest --exclude-dir=docs --exclude-dir=test --exclude-dir=tests "${dir}" -e "\"http://${endpoint}.[^\"']*\"" -e "'http://${endpoint}.[^\"']*'")
    local https_files=$(grep -rnlI --exclude=*.json --exclude=*.md --exclude=*.swift --exclude-dir=androidTest --exclude-dir=docs --exclude-dir=test --exclude-dir=tests "${dir}" -e "\"https://${endpoint}[^\"']*\"" -e "'https://${endpoint}[^\"']*'")
    local https_files_slash=$(grep -rnlI --exclude=*.json --exclude=*.md --exclude=*.swift --exclude-dir=androidTest --exclude-dir=docs --exclude-dir=test --exclude-dir=tests "${dir}" -e "\"https://${endpoint}/[^\"']*\"" -e "'https://${endpoint}/[^\"']*'")
    local https_files_period=$(grep -rnlI --exclude=*.json --exclude=*.md --exclude=*.swift --exclude-dir=androidTest --exclude-dir=docs --exclude-dir=test --exclude-dir=tests "${dir}" -e "\"https://${endpoint}.[^\"']*\"" -e "'https://${endpoint}.[^\"']*'")

    # Check if any files were found and modify them
    if [ -n "$files" ]; then
        echo "Removing $endpoint from files... $files"
        echo "$files" | xargs -L1 "$SED" -i -r -e "s|\"${endpoint}[^\"']*\"|\"\"|g" -e "s|'${endpoint}[^\"']*'|''|g"
    fi

    if [ -n "$files_slash" ]; then
        echo "Removing $endpoint/ from files... $files_slash"
        echo "$files_slash" | xargs -L1 "$SED" -i -r -e "s|\"${endpoint}/[^\"']*\"|\"\"|g" -e "s|'${endpoint}/[^\"']*'|''|g"
    fi

    if [ -n "$files_period" ]; then
        echo "Removing $endpoint. from files... $files_period"
        echo "$files_period" | xargs -L1 "$SED" -i -r -e "s|\"${endpoint}.[^\"']*\"|\"\"|g" -e "s|'${endpoint}.[^\"']*'|''|g"
    fi

    if [ -n "$http_files" ]; then
        echo "Removing http://$endpoint from files... $http_files"
        echo "$http_files" | xargs -L1 "$SED" -i -r -e "s|\"http://${endpoint}[^\"']*\"|\"\"|g" -e "s|'http://${endpoint}[^\"']*'|''|g"
    fi

    if [ -n "$http_files_slash" ]; then
        echo "Removing http://$endpoint/ from files... $http_files_slash"
        echo "$http_files_slash" | xargs -L1 "$SED" -i -r -e "s|\"http://${endpoint}/[^\"']*\"|\"\"|g" -e "s|'http://${endpoint}/[^\"']*'|''|g"
    fi

    if [ -n "$http_files_period" ]; then
        echo "Removing http://$endpoint. from files... $http_files_period"
        echo "$http_files_period" | xargs -L1 "$SED" -i -r -e "s|\"http://${endpoint}.[^\"']*\"|\"\"|g" -e "s|'http://${endpoint}.[^\"']*'|''|g"
    fi

    if [ -n "$https_files" ]; then
        echo "Removing https://$endpoint from files... $https_files"
        echo "$https_files" | xargs -L1 "$SED" -i -r -e "s|\"https://${endpoint}[^\"']*\"|\"\"|g" -e "s|'https://${endpoint}[^\"']*'|''|g"
    fi

    if [ -n "$https_files_slash" ]; then
        echo "Removing https://$endpoint/ from files... $https_files_slash"
        echo "$https_files_slash" | xargs -L1 "$SED" -i -r -e "s|\"https://${endpoint}/[^\"']*\"|\"\"|g" -e "s|'https://${endpoint}/[^\"']*'|''|g"
    fi

    if [ -n "$https_files_period" ]; then
        echo "Removing https://$endpoint. from files... $https_files_period"
        echo "$https_files_period" | xargs -L1 "$SED" -i -r -e "s|\"https://${endpoint}.[^\"']*\"|\"\"|g" -e "s|'https://${endpoint}.[^\"']*'|''|g"
    fi
}

## AMO Discovery/recommendations
noop_mozilla_endpoints "discovery.addons.allizom.org" "${application_services}"
noop_mozilla_endpoints "discovery.addons.allizom.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "discovery.addons.allizom.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "discovery.addons.allizom.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "discovery.addons.allizom.org" "${mozilla_release}/python"
noop_mozilla_endpoints "discovery.addons.allizom.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "discovery.addons.allizom.org" "${glean}"
noop_mozilla_endpoints "discovery.addons.mozilla.org" "${application_services}"
noop_mozilla_endpoints "discovery.addons.mozilla.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "discovery.addons.mozilla.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "discovery.addons.mozilla.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "discovery.addons.mozilla.org" "${mozilla_release}/python"
noop_mozilla_endpoints "discovery.addons.mozilla.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "discovery.addons.mozilla.org" "${glean}"
noop_mozilla_endpoints "discovery.addons-dev.allizom.org" "${application_services}"
noop_mozilla_endpoints "discovery.addons-dev.allizom.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "discovery.addons-dev.allizom.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "discovery.addons-dev.allizom.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "discovery.addons-dev.allizom.org" "${mozilla_release}/python"
noop_mozilla_endpoints "discovery.addons-dev.allizom.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "discovery.addons-dev.allizom.org" "${glean}"

## ASan crash reporting
noop_mozilla_endpoints "anf1.fuzzing.mozilla.org" "${application_services}"
noop_mozilla_endpoints "anf1.fuzzing.mozilla.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "anf1.fuzzing.mozilla.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "anf1.fuzzing.mozilla.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "anf1.fuzzing.mozilla.org" "${mozilla_release}/python"
noop_mozilla_endpoints "anf1.fuzzing.mozilla.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "anf1.fuzzing.mozilla.org" "${glean}"

## Connectivity checks
noop_mozilla_endpoints "detectportal.firefox.com" "${application_services}"
noop_mozilla_endpoints "detectportal.firefox.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "detectportal.firefox.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "detectportal.firefox.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "detectportal.firefox.com" "${mozilla_release}/python"
noop_mozilla_endpoints "detectportal.firefox.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "detectportal.firefox.com" "${glean}"

## Contile
noop_mozilla_endpoints "contile.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "contile.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "contile.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "contile.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "contile.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "contile.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "contile.services.mozilla.com" "${glean}"
noop_mozilla_endpoints "contile-images.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "contile-images.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "contile-images.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "contile-images.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "contile-images.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "contile-images.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "contile-images.services.mozilla.com" "${glean}"

## Crash reporting
noop_mozilla_endpoints "crash-reports.allizom.org" "${application_services}"
noop_mozilla_endpoints "crash-reports.allizom.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "crash-reports.allizom.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "crash-reports.allizom.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "crash-reports.allizom.org" "${mozilla_release}/python"
noop_mozilla_endpoints "crash-reports.allizom.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "crash-reports.allizom.org" "${glean}"
noop_mozilla_endpoints "crash-reports.mozilla.com" "${application_services}"
noop_mozilla_endpoints "crash-reports.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "crash-reports.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "crash-reports.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "crash-reports.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "crash-reports.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "crash-reports.mozilla.com" "${glean}"
noop_mozilla_endpoints "crash-reports-xpsp2.mozilla.com" "${application_services}"
noop_mozilla_endpoints "crash-reports-xpsp2.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "crash-reports-xpsp2.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "crash-reports-xpsp2.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "crash-reports-xpsp2.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "crash-reports-xpsp2.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "crash-reports-xpsp2.mozilla.com" "${glean}"
noop_mozilla_endpoints "crash-stacks.mozilla.com" "${application_services}"
noop_mozilla_endpoints "crash-stacks.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "crash-stacks.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "crash-stacks.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "crash-stacks.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "crash-stacks.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "crash-stacks.mozilla.com" "${glean}"
noop_mozilla_endpoints "crash-stats.allizom.org" "${application_services}"
noop_mozilla_endpoints "crash-stats.allizom.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "crash-stats.allizom.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "crash-stats.allizom.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "crash-stats.allizom.org" "${mozilla_release}/python"
noop_mozilla_endpoints "crash-stats.allizom.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "crash-stats.allizom.org" "${glean}"
noop_mozilla_endpoints "crash-stats.mozilla.com" "${application_services}"
noop_mozilla_endpoints "crash-stats.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "crash-stats.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "crash-stats.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "crash-stats.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "crash-stats.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "crash-stats.mozilla.com" "${glean}"
noop_mozilla_endpoints "crash-stats.mozilla.org" "${application_services}"
noop_mozilla_endpoints "crash-stats.mozilla.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "crash-stats.mozilla.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "crash-stats.mozilla.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "crash-stats.mozilla.org" "${mozilla_release}/python"
noop_mozilla_endpoints "crash-stats.mozilla.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "crash-stats.mozilla.org" "${glean}"
noop_mozilla_endpoints "socorro.prod.webservices.mozgcp.net" "${application_services}"
noop_mozilla_endpoints "socorro.prod.webservices.mozgcp.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "socorro.prod.webservices.mozgcp.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "socorro.prod.webservices.mozgcp.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "socorro.prod.webservices.mozgcp.net" "${mozilla_release}/python"
noop_mozilla_endpoints "socorro.prod.webservices.mozgcp.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "socorro.prod.webservices.mozgcp.net" "${glean}"
noop_mozilla_endpoints "socorro-collector.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "socorro-collector.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "socorro-collector.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "socorro-collector.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "socorro-collector.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "socorro-collector.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "socorro-collector.services.mozilla.com" "${glean}"
noop_mozilla_endpoints "socorro-webapp.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "socorro-webapp.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "socorro-webapp.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "socorro-webapp.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "socorro-webapp.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "socorro-webapp.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "socorro-webapp.services.mozilla.com" "${glean}"
noop_mozilla_endpoints "socorro-webapp-allizom.stage.mozaws.net" "${application_services}"
noop_mozilla_endpoints "socorro-webapp-allizom.stage.mozaws.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "socorro-webapp-allizom.stage.mozaws.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "socorro-webapp-allizom.stage.mozaws.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "socorro-webapp-allizom.stage.mozaws.net" "${mozilla_release}/python"
noop_mozilla_endpoints "socorro-webapp-allizom.stage.mozaws.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "socorro-webapp-allizom.stage.mozaws.net" "${glean}"
noop_mozilla_endpoints "talkback.mozilla.org" "${application_services}"
noop_mozilla_endpoints "talkback.mozilla.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "talkback.mozilla.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "talkback.mozilla.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "talkback.mozilla.org" "${mozilla_release}/python"
noop_mozilla_endpoints "talkback.mozilla.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "talkback.mozilla.org" "${glean}"
noop_mozilla_endpoints "talkback-public.mozilla.org" "${application_services}"
noop_mozilla_endpoints "talkback-public.mozilla.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "talkback-public.mozilla.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "talkback-public.mozilla.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "talkback-public.mozilla.org" "${mozilla_release}/python"
noop_mozilla_endpoints "talkback-public.mozilla.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "talkback-public.mozilla.org" "${glean}"
noop_mozilla_endpoints "talkback-reports.mozilla.org" "${application_services}"
noop_mozilla_endpoints "talkback-reports.mozilla.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "talkback-reports.mozilla.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "talkback-reports.mozilla.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "talkback-reports.mozilla.org" "${mozilla_release}/python"
noop_mozilla_endpoints "talkback-reports.mozilla.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "talkback-reports.mozilla.org" "${glean}"

## DoH canary requests
noop_mozilla_endpoints "sitereview.zscaler.com" "${application_services}"
noop_mozilla_endpoints "sitereview.zscaler.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "sitereview.zscaler.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "sitereview.zscaler.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "sitereview.zscaler.com" "${mozilla_release}/python"
noop_mozilla_endpoints "sitereview.zscaler.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "sitereview.zscaler.com" "${glean}"
noop_mozilla_endpoints "use-application-dns.net" "${application_services}"
noop_mozilla_endpoints "use-application-dns.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "use-application-dns.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "use-application-dns.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "use-application-dns.net" "${mozilla_release}/python"
noop_mozilla_endpoints "use-application-dns.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "use-application-dns.net" "${glean}"

## DoH performance tests
noop_mozilla_endpoints "firefox-dns-perf-test.net" "${application_services}"
noop_mozilla_endpoints "firefox-dns-perf-test.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "firefox-dns-perf-test.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "firefox-dns-perf-test.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "firefox-dns-perf-test.net" "${mozilla_release}/python"
noop_mozilla_endpoints "firefox-dns-perf-test.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "firefox-dns-perf-test.net" "${glean}"

## GeoIP
noop_mozilla_endpoints "classify-client.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "classify-client.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "classify-client.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "classify-client.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "classify-client.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "classify-client.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "classify-client.services.mozilla.com" "${glean}"
noop_mozilla_endpoints "location.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "location.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "location.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "location.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "location.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "location.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "location.services.mozilla.com" "${glean}"
noop_mozilla_endpoints "locprod1-elb-eu-west-1.prod.mozaws.net" "${application_services}"
noop_mozilla_endpoints "locprod1-elb-eu-west-1.prod.mozaws.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "locprod1-elb-eu-west-1.prod.mozaws.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "locprod1-elb-eu-west-1.prod.mozaws.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "locprod1-elb-eu-west-1.prod.mozaws.net" "${mozilla_release}/python"
noop_mozilla_endpoints "locprod1-elb-eu-west-1.prod.mozaws.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "locprod1-elb-eu-west-1.prod.mozaws.net" "${glean}"
noop_mozilla_endpoints "locprod2-elb-us-west-2.prod.mozaws.net" "${application_services}"
noop_mozilla_endpoints "locprod2-elb-us-west-2.prod.mozaws.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "locprod2-elb-us-west-2.prod.mozaws.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "locprod2-elb-us-west-2.prod.mozaws.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "locprod2-elb-us-west-2.prod.mozaws.net" "${mozilla_release}/python"
noop_mozilla_endpoints "locprod2-elb-us-west-2.prod.mozaws.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "locprod2-elb-us-west-2.prod.mozaws.net" "${glean}"
noop_mozilla_endpoints "nonprod.classify-client.nonprod.webservices.mozgcp.net" "${application_services}"
noop_mozilla_endpoints "nonprod.classify-client.nonprod.webservices.mozgcp.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "nonprod.classify-client.nonprod.webservices.mozgcp.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "nonprod.classify-client.nonprod.webservices.mozgcp.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "nonprod.classify-client.nonprod.webservices.mozgcp.net" "${mozilla_release}/python"
noop_mozilla_endpoints "nonprod.classify-client.nonprod.webservices.mozgcp.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "nonprod.classify-client.nonprod.webservices.mozgcp.net" "${glean}"
noop_mozilla_endpoints "prod.classify-client.prod.webservices.mozgcp.net" "${application_services}"
noop_mozilla_endpoints "prod.classify-client.prod.webservices.mozgcp.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "prod.classify-client.prod.webservices.mozgcp.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "prod.classify-client.prod.webservices.mozgcp.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "prod.classify-client.prod.webservices.mozgcp.net" "${mozilla_release}/python"
noop_mozilla_endpoints "prod.classify-client.prod.webservices.mozgcp.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "prod.classify-client.prod.webservices.mozgcp.net" "${glean}"
noop_mozilla_endpoints "search.r53-2.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "search.r53-2.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "search.r53-2.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "search.r53-2.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "search.r53-2.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "search.r53-2.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "search.r53-2.services.mozilla.com" "${glean}"
noop_mozilla_endpoints "search.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "search.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "search.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "search.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "search.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "search.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "search.services.mozilla.com" "${glean}"

## Icons
noop_mozilla_endpoints "activity-stream-icons.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "activity-stream-icons.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "activity-stream-icons.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "activity-stream-icons.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "activity-stream-icons.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "activity-stream-icons.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "activity-stream-icons.services.mozilla.com" "${glean}"

## MARS
noop_mozilla_endpoints "ads.allizom.org" "${application_services}"
noop_mozilla_endpoints "ads.allizom.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "ads.allizom.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "ads.allizom.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "ads.allizom.org" "${mozilla_release}/python"
noop_mozilla_endpoints "ads.allizom.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "ads.allizom.org" "${glean}"
noop_mozilla_endpoints "ads.mozilla.org" "${application_services}"
noop_mozilla_endpoints "ads.mozilla.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "ads.mozilla.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "ads.mozilla.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "ads.mozilla.org" "${mozilla_release}/python"
noop_mozilla_endpoints "ads.mozilla.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "ads.mozilla.org" "${glean}"
noop_mozilla_endpoints "ads.nonprod.webservices.mozgcp.net" "${application_services}"
noop_mozilla_endpoints "ads.nonprod.webservices.mozgcp.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "ads.nonprod.webservices.mozgcp.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "ads.nonprod.webservices.mozgcp.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "ads.nonprod.webservices.mozgcp.net" "${mozilla_release}/python"
noop_mozilla_endpoints "ads.nonprod.webservices.mozgcp.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "ads.nonprod.webservices.mozgcp.net" "${glean}"
noop_mozilla_endpoints "ads-img.mozilla.org" "${application_services}"
noop_mozilla_endpoints "ads-img.mozilla.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "ads-img.mozilla.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "ads-img.mozilla.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "ads-img.mozilla.org" "${mozilla_release}/python"
noop_mozilla_endpoints "ads-img.mozilla.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "ads-img.mozilla.org" "${glean}"
noop_mozilla_endpoints "tiles-cdn.prod.ads.prod.webservices.mozgcp.net" "${application_services}"
noop_mozilla_endpoints "tiles-cdn.prod.ads.prod.webservices.mozgcp.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "tiles-cdn.prod.ads.prod.webservices.mozgcp.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "tiles-cdn.prod.ads.prod.webservices.mozgcp.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "tiles-cdn.prod.ads.prod.webservices.mozgcp.net" "${mozilla_release}/python"
noop_mozilla_endpoints "tiles-cdn.prod.ads.prod.webservices.mozgcp.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "tiles-cdn.prod.ads.prod.webservices.mozgcp.net" "${glean}"

## Normandy (Experimentation)
noop_mozilla_endpoints "normandy.cdn.mozilla.net" "${application_services}"
noop_mozilla_endpoints "normandy.cdn.mozilla.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "normandy.cdn.mozilla.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "normandy.cdn.mozilla.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "normandy.cdn.mozilla.net" "${mozilla_release}/python"
noop_mozilla_endpoints "normandy.cdn.mozilla.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "normandy.cdn.mozilla.net" "${glean}"
noop_mozilla_endpoints "normandy.nonprod.cloudops.mozgcp.net" "${application_services}"
noop_mozilla_endpoints "normandy.nonprod.cloudops.mozgcp.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "normandy.nonprod.cloudops.mozgcp.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "normandy.nonprod.cloudops.mozgcp.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "normandy.nonprod.cloudops.mozgcp.net" "${mozilla_release}/python"
noop_mozilla_endpoints "normandy.nonprod.cloudops.mozgcp.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "normandy.nonprod.cloudops.mozgcp.net" "${glean}"
noop_mozilla_endpoints "normandy-cdn.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "normandy-cdn.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "normandy-cdn.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "normandy-cdn.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "normandy-cdn.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "normandy-cdn.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "normandy-cdn.services.mozilla.com" "${glean}"
noop_mozilla_endpoints "prod-classifyclient.normandy.prod.cloudops.mozgcp.net" "${application_services}"
noop_mozilla_endpoints "prod-classifyclient.normandy.prod.cloudops.mozgcp.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "prod-classifyclient.normandy.prod.cloudops.mozgcp.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "prod-classifyclient.normandy.prod.cloudops.mozgcp.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "prod-classifyclient.normandy.prod.cloudops.mozgcp.net" "${mozilla_release}/python"
noop_mozilla_endpoints "prod-classifyclient.normandy.prod.cloudops.mozgcp.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "prod-classifyclient.normandy.prod.cloudops.mozgcp.net" "${glean}"

## Pocket
noop_mozilla_endpoints "firefox-android-home-recommendations.getpocket.com" "${application_services}"
noop_mozilla_endpoints "firefox-android-home-recommendations.getpocket.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "firefox-android-home-recommendations.getpocket.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "firefox-android-home-recommendations.getpocket.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "firefox-android-home-recommendations.getpocket.com" "${mozilla_release}/python"
noop_mozilla_endpoints "firefox-android-home-recommendations.getpocket.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "firefox-android-home-recommendations.getpocket.com" "${glean}"
noop_mozilla_endpoints "img-getpocket.cdn.mozilla.net" "${application_services}"
noop_mozilla_endpoints "img-getpocket.cdn.mozilla.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "img-getpocket.cdn.mozilla.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "img-getpocket.cdn.mozilla.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "img-getpocket.cdn.mozilla.net" "${mozilla_release}/python"
noop_mozilla_endpoints "img-getpocket.cdn.mozilla.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "img-getpocket.cdn.mozilla.net" "${glean}"
noop_mozilla_endpoints "spocs.getpocket.com" "${application_services}"
noop_mozilla_endpoints "spocs.getpocket.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "spocs.getpocket.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "spocs.getpocket.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "spocs.getpocket.com" "${mozilla_release}/python"
noop_mozilla_endpoints "spocs.getpocket.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "spocs.getpocket.com" "${glean}"
noop_mozilla_endpoints "spocs.getpocket.dev" "${application_services}"
noop_mozilla_endpoints "spocs.getpocket.dev" "${mozilla_release}/mobile"
noop_mozilla_endpoints "spocs.getpocket.dev" "${mozilla_release}/modules"
noop_mozilla_endpoints "spocs.getpocket.dev" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "spocs.getpocket.dev" "${mozilla_release}/python"
noop_mozilla_endpoints "spocs.getpocket.dev" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "spocs.getpocket.dev" "${glean}"
noop_mozilla_endpoints "spocs.mozilla.net" "${application_services}"
noop_mozilla_endpoints "spocs.mozilla.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "spocs.mozilla.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "spocs.mozilla.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "spocs.mozilla.net" "${mozilla_release}/python"
noop_mozilla_endpoints "spocs.mozilla.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "spocs.mozilla.net" "${glean}"

## Sentry
noop_mozilla_endpoints "5cfe351fb3a24e8d82c751252b48722b@o1069899.ingest.sentry.io" "${application_services}"
noop_mozilla_endpoints "5cfe351fb3a24e8d82c751252b48722b@o1069899.ingest.sentry.io" "${mozilla_release}/mobile"
noop_mozilla_endpoints "5cfe351fb3a24e8d82c751252b48722b@o1069899.ingest.sentry.io" "${mozilla_release}/modules"
noop_mozilla_endpoints "5cfe351fb3a24e8d82c751252b48722b@o1069899.ingest.sentry.io" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "5cfe351fb3a24e8d82c751252b48722b@o1069899.ingest.sentry.io" "${mozilla_release}/python"
noop_mozilla_endpoints "5cfe351fb3a24e8d82c751252b48722b@o1069899.ingest.sentry.io" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "5cfe351fb3a24e8d82c751252b48722b@o1069899.ingest.sentry.io" "${glean}"
noop_mozilla_endpoints "o1069899.ingest.sentry.io" "${application_services}"
noop_mozilla_endpoints "o1069899.ingest.sentry.io" "${mozilla_release}/mobile"
noop_mozilla_endpoints "o1069899.ingest.sentry.io" "${mozilla_release}/modules"
noop_mozilla_endpoints "o1069899.ingest.sentry.io" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "o1069899.ingest.sentry.io" "${mozilla_release}/python"
noop_mozilla_endpoints "o1069899.ingest.sentry.io" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "o1069899.ingest.sentry.io" "${glean}"
noop_mozilla_endpoints "prod.sentry.prod.cloudops.mozgcp.net" "${application_services}"
noop_mozilla_endpoints "prod.sentry.prod.cloudops.mozgcp.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "prod.sentry.prod.cloudops.mozgcp.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "prod.sentry.prod.cloudops.mozgcp.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "prod.sentry.prod.cloudops.mozgcp.net" "${mozilla_release}/python"
noop_mozilla_endpoints "prod.sentry.prod.cloudops.mozgcp.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "prod.sentry.prod.cloudops.mozgcp.net" "${glean}"
noop_mozilla_endpoints "sentry.io" "${application_services}"
noop_mozilla_endpoints "sentry.io" "${mozilla_release}/mobile"
noop_mozilla_endpoints "sentry.io" "${mozilla_release}/modules"
noop_mozilla_endpoints "sentry.io" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "sentry.io" "${mozilla_release}/python"
noop_mozilla_endpoints "sentry.io" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "sentry.io" "${glean}"
noop_mozilla_endpoints "stage.sentry.nonprod.cloudops.mozgcp.net" "${application_services}"
noop_mozilla_endpoints "stage.sentry.nonprod.cloudops.mozgcp.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "stage.sentry.nonprod.cloudops.mozgcp.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "stage.sentry.nonprod.cloudops.mozgcp.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "stage.sentry.nonprod.cloudops.mozgcp.net" "${mozilla_release}/python"
noop_mozilla_endpoints "stage.sentry.nonprod.cloudops.mozgcp.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "stage.sentry.nonprod.cloudops.mozgcp.net" "${glean}"

## Snippets
noop_mozilla_endpoints "snippets.allizom.org" "${application_services}"
noop_mozilla_endpoints "snippets.allizom.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "snippets.allizom.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "snippets.allizom.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "snippets.allizom.org" "${mozilla_release}/python"
noop_mozilla_endpoints "snippets.allizom.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "snippets.allizom.org" "${glean}"
noop_mozilla_endpoints "snippets.cdn.mozilla.net" "${application_services}"
noop_mozilla_endpoints "snippets.cdn.mozilla.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "snippets.cdn.mozilla.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "snippets.cdn.mozilla.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "snippets.cdn.mozilla.net" "${mozilla_release}/python"
noop_mozilla_endpoints "snippets.cdn.mozilla.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "snippets.cdn.mozilla.net" "${glean}"
noop_mozilla_endpoints "snippets.mozilla.com" "${application_services}"
noop_mozilla_endpoints "snippets.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "snippets.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "snippets.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "snippets.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "snippets.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "snippets.mozilla.com" "${glean}"
noop_mozilla_endpoints "snippets-prod.frankfurt.moz.works" "${application_services}"
noop_mozilla_endpoints "snippets-prod.frankfurt.moz.works" "${mozilla_release}/mobile"
noop_mozilla_endpoints "snippets-prod.frankfurt.moz.works" "${mozilla_release}/modules"
noop_mozilla_endpoints "snippets-prod.frankfurt.moz.works" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "snippets-prod.frankfurt.moz.works" "${mozilla_release}/python"
noop_mozilla_endpoints "snippets-prod.frankfurt.moz.works" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "snippets-prod.frankfurt.moz.works" "${glean}"
noop_mozilla_endpoints "snippets-prod.moz.works" "${application_services}"
noop_mozilla_endpoints "snippets-prod.moz.works" "${mozilla_release}/mobile"
noop_mozilla_endpoints "snippets-prod.moz.works" "${mozilla_release}/modules"
noop_mozilla_endpoints "snippets-prod.moz.works" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "snippets-prod.moz.works" "${mozilla_release}/python"
noop_mozilla_endpoints "snippets-prod.moz.works" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "snippets-prod.moz.works" "${glean}"
noop_mozilla_endpoints "snippets-prod.oregon-b.moz.works" "${application_services}"
noop_mozilla_endpoints "snippets-prod.oregon-b.moz.works" "${mozilla_release}/mobile"
noop_mozilla_endpoints "snippets-prod.oregon-b.moz.works" "${mozilla_release}/modules"
noop_mozilla_endpoints "snippets-prod.oregon-b.moz.works" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "snippets-prod.oregon-b.moz.works" "${mozilla_release}/python"
noop_mozilla_endpoints "snippets-prod.oregon-b.moz.works" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "snippets-prod.oregon-b.moz.works" "${glean}"
noop_mozilla_endpoints "snippets-stage.moz.works" "${application_services}"
noop_mozilla_endpoints "snippets-stage.moz.works" "${mozilla_release}/mobile"
noop_mozilla_endpoints "snippets-stage.moz.works" "${mozilla_release}/modules"
noop_mozilla_endpoints "snippets-stage.moz.works" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "snippets-stage.moz.works" "${mozilla_release}/python"
noop_mozilla_endpoints "snippets-stage.moz.works" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "snippets-stage.moz.works" "${glean}"
noop_mozilla_endpoints "snippets-stage.oregon-b.moz.works" "${application_services}"
noop_mozilla_endpoints "snippets-stage.oregon-b.moz.works" "${mozilla_release}/mobile"
noop_mozilla_endpoints "snippets-stage.oregon-b.moz.works" "${mozilla_release}/modules"
noop_mozilla_endpoints "snippets-stage.oregon-b.moz.works" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "snippets-stage.oregon-b.moz.works" "${mozilla_release}/python"
noop_mozilla_endpoints "snippets-stage.oregon-b.moz.works" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "snippets-stage.oregon-b.moz.works" "${glean}"

## Surveys
noop_mozilla_endpoints "survey.mozilla.com" "${application_services}"
noop_mozilla_endpoints "survey.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "survey.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "survey.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "survey.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "survey.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "survey.mozilla.com" "${glean}"

## Telemetry
noop_mozilla_endpoints "coverage.mozilla.org" "${application_services}"
noop_mozilla_endpoints "coverage.mozilla.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "coverage.mozilla.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "coverage.mozilla.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "coverage.mozilla.org" "${mozilla_release}/python"
noop_mozilla_endpoints "coverage.mozilla.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "coverage.mozilla.org" "${glean}"
noop_mozilla_endpoints "dap-09-3.api.divviup.org" "${application_services}"
noop_mozilla_endpoints "dap-09-3.api.divviup.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "dap-09-3.api.divviup.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "dap-09-3.api.divviup.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "dap-09-3.api.divviup.org" "${mozilla_release}/python"
noop_mozilla_endpoints "dap-09-3.api.divviup.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "dap-09-3.api.divviup.org" "${glean}"
noop_mozilla_endpoints "dap.nonprod.webservices.mozgcp.net" "${application_services}"
noop_mozilla_endpoints "dap.nonprod.webservices.mozgcp.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "dap.nonprod.webservices.mozgcp.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "dap.nonprod.webservices.mozgcp.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "dap.nonprod.webservices.mozgcp.net" "${mozilla_release}/python"
noop_mozilla_endpoints "dap.nonprod.webservices.mozgcp.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "dap.nonprod.webservices.mozgcp.net" "${glean}"
noop_mozilla_endpoints "dap.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "dap.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "dap.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "dap.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "dap.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "dap.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "dap.services.mozilla.com" "${glean}"
noop_mozilla_endpoints "debug-ping-preview.firebaseapp.com" "${application_services}"
noop_mozilla_endpoints "debug-ping-preview.firebaseapp.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "debug-ping-preview.firebaseapp.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "debug-ping-preview.firebaseapp.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "debug-ping-preview.firebaseapp.com" "${mozilla_release}/python"
noop_mozilla_endpoints "debug-ping-preview.firebaseapp.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "debug-ping-preview.firebaseapp.com" "${glean}"
noop_mozilla_endpoints "download-stats.mozilla.org" "${application_services}"
noop_mozilla_endpoints "download-stats.mozilla.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "download-stats.mozilla.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "download-stats.mozilla.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "download-stats.mozilla.org" "${mozilla_release}/python"
noop_mozilla_endpoints "download-stats.mozilla.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "download-stats.mozilla.org" "${glean}"
noop_mozilla_endpoints "download-stats.r53-2.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "download-stats.r53-2.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "download-stats.r53-2.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "download-stats.r53-2.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "download-stats.r53-2.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "download-stats.r53-2.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "download-stats.r53-2.services.mozilla.com" "${glean}"
noop_mozilla_endpoints "fhr.data.mozilla.com" "${application_services}"
noop_mozilla_endpoints "fhr.data.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "fhr.data.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "fhr.data.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "fhr.data.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "fhr.data.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "fhr.data.mozilla.com" "${glean}"
noop_mozilla_endpoints "fhr.r53-2.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "fhr.r53-2.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "fhr.r53-2.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "fhr.r53-2.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "fhr.r53-2.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "fhr.r53-2.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "fhr.r53-2.services.mozilla.com" "${glean}"
noop_mozilla_endpoints "firefox.settings.services.allizom.org" "${mozilla_release}/toolkit/components/glean"
noop_mozilla_endpoints "firefox.settings.services.allizom.org" "${mozilla_release}/toolkit/components/telemetry"
noop_mozilla_endpoints "firefox.settings.services.allizom.org" "${glean}"
noop_mozilla_endpoints "firefox.settings.services.mozilla.com" "${mozilla_release}/toolkit/components/glean"
noop_mozilla_endpoints "firefox.settings.services.mozilla.com" "${mozilla_release}/toolkit/components/telemetry"
noop_mozilla_endpoints "firefox.settings.services.mozilla.com" "${glean}"
noop_mozilla_endpoints "incoming.glean.example.com" "${application_services}"
noop_mozilla_endpoints "incoming.glean.example.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "incoming.glean.example.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "incoming.glean.example.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "incoming.glean.example.com" "${mozilla_release}/python"
noop_mozilla_endpoints "incoming.glean.example.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "incoming.glean.example.com" "${glean}"
noop_mozilla_endpoints "incoming.telemetry.mozilla.org" "${application_services}"
noop_mozilla_endpoints "incoming.telemetry.mozilla.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "incoming.telemetry.mozilla.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "incoming.telemetry.mozilla.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "incoming.telemetry.mozilla.org" "${mozilla_release}/python"
noop_mozilla_endpoints "incoming.telemetry.mozilla.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "incoming.telemetry.mozilla.org" "${glean}"
noop_mozilla_endpoints "incoming.thunderbird.net" "${application_services}"
noop_mozilla_endpoints "incoming.thunderbird.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "incoming.thunderbird.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "incoming.thunderbird.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "incoming.thunderbird.net" "${mozilla_release}/python"
noop_mozilla_endpoints "incoming.thunderbird.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "incoming.thunderbird.net" "${glean}"
noop_mozilla_endpoints "incoming-telemetry.thunderbird.net" "${application_services}"
noop_mozilla_endpoints "incoming-telemetry.thunderbird.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "incoming-telemetry.thunderbird.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "incoming-telemetry.thunderbird.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "incoming-telemetry.thunderbird.net" "${mozilla_release}/python"
noop_mozilla_endpoints "incoming-telemetry.thunderbird.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "incoming-telemetry.thunderbird.net" "${glean}"
noop_mozilla_endpoints "mozilla-ohttp.fastly-edge.com" "${mozilla_release}/toolkit/components/glean"
noop_mozilla_endpoints "mozilla-ohttp.fastly-edge.com" "${mozilla_release}/toolkit/components/telemetry"
noop_mozilla_endpoints "mozilla-ohttp.fastly-edge.com" "${glean}"
noop_mozilla_endpoints "prod.dap.prod.webservices.mozgcp.net" "${application_services}"
noop_mozilla_endpoints "prod.dap.prod.webservices.mozgcp.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "prod.dap.prod.webservices.mozgcp.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "prod.dap.prod.webservices.mozgcp.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "prod.dap.prod.webservices.mozgcp.net" "${mozilla_release}/python"
noop_mozilla_endpoints "prod.dap.prod.webservices.mozgcp.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "prod.dap.prod.webservices.mozgcp.net" "${glean}"
noop_mozilla_endpoints "prod.data-ingestion.prod.dataops.mozgcp.net" "${application_services}"
noop_mozilla_endpoints "prod.data-ingestion.prod.dataops.mozgcp.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "prod.data-ingestion.prod.dataops.mozgcp.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "prod.data-ingestion.prod.dataops.mozgcp.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "prod.data-ingestion.prod.dataops.mozgcp.net" "${mozilla_release}/python"
noop_mozilla_endpoints "prod.data-ingestion.prod.dataops.mozgcp.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "prod.data-ingestion.prod.dataops.mozgcp.net" "${glean}"
noop_mozilla_endpoints "prod.ingestion-edge.prod.dataops.mozgcp.net" "${application_services}"
noop_mozilla_endpoints "prod.ingestion-edge.prod.dataops.mozgcp.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "prod.ingestion-edge.prod.dataops.mozgcp.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "prod.ingestion-edge.prod.dataops.mozgcp.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "prod.ingestion-edge.prod.dataops.mozgcp.net" "${mozilla_release}/python"
noop_mozilla_endpoints "prod.ingestion-edge.prod.dataops.mozgcp.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "prod.ingestion-edge.prod.dataops.mozgcp.net" "${glean}"
noop_mozilla_endpoints "prod.ohttp-gateway.prod.webservices.mozgcp.net" "${mozilla_release}/toolkit/components/glean"
noop_mozilla_endpoints "prod.ohttp-gateway.prod.webservices.mozgcp.net" "${mozilla_release}/toolkit/components/telemetry"
noop_mozilla_endpoints "prod.ohttp-gateway.prod.webservices.mozgcp.net" "${glean}"
noop_mozilla_endpoints "self-repair.mozilla.org" "${application_services}"
noop_mozilla_endpoints "self-repair.mozilla.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "self-repair.mozilla.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "self-repair.mozilla.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "self-repair.mozilla.org" "${mozilla_release}/python"
noop_mozilla_endpoints "self-repair.mozilla.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "self-repair.mozilla.org" "${glean}"
noop_mozilla_endpoints "self-repair.r53-2.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "self-repair.r53-2.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "self-repair.r53-2.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "self-repair.r53-2.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "self-repair.r53-2.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "self-repair.r53-2.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "self-repair.r53-2.services.mozilla.com" "${glean}"
noop_mozilla_endpoints "telemetry-coverage.mozilla.org" "${application_services}"
noop_mozilla_endpoints "telemetry-coverage.mozilla.org" "${mozilla_release}/mobile"
noop_mozilla_endpoints "telemetry-coverage.mozilla.org" "${mozilla_release}/modules"
noop_mozilla_endpoints "telemetry-coverage.mozilla.org" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "telemetry-coverage.mozilla.org" "${mozilla_release}/python"
noop_mozilla_endpoints "telemetry-coverage.mozilla.org" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "telemetry-coverage.mozilla.org" "${glean}"
noop_mozilla_endpoints "telemetry-coverage.r53-2.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "telemetry-coverage.r53-2.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "telemetry-coverage.r53-2.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "telemetry-coverage.r53-2.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "telemetry-coverage.r53-2.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "telemetry-coverage.r53-2.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "telemetry-coverage.r53-2.services.mozilla.com" "${glean}"
noop_mozilla_endpoints "telemetry-experiment.cdn.mozilla.net" "${application_services}"
noop_mozilla_endpoints "telemetry-experiment.cdn.mozilla.net" "${mozilla_release}/mobile"
noop_mozilla_endpoints "telemetry-experiment.cdn.mozilla.net" "${mozilla_release}/modules"
noop_mozilla_endpoints "telemetry-experiment.cdn.mozilla.net" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "telemetry-experiment.cdn.mozilla.net" "${mozilla_release}/python"
noop_mozilla_endpoints "telemetry-experiment.cdn.mozilla.net" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "telemetry-experiment.cdn.mozilla.net" "${glean}"
noop_mozilla_endpoints "telemetry-incoming.r53-2.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "telemetry-incoming.r53-2.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "telemetry-incoming.r53-2.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "telemetry-incoming.r53-2.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "telemetry-incoming.r53-2.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "telemetry-incoming.r53-2.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "telemetry-incoming.r53-2.services.mozilla.com" "${glean}"
noop_mozilla_endpoints "telemetry-incoming-a.r53-2.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "telemetry-incoming-a.r53-2.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "telemetry-incoming-a.r53-2.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "telemetry-incoming-a.r53-2.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "telemetry-incoming-a.r53-2.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "telemetry-incoming-a.r53-2.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "telemetry-incoming-a.r53-2.services.mozilla.com" "${glean}"
noop_mozilla_endpoints "telemetry-incoming-b.r53-2.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "telemetry-incoming-b.r53-2.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "telemetry-incoming-b.r53-2.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "telemetry-incoming-b.r53-2.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "telemetry-incoming-b.r53-2.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "telemetry-incoming-b.r53-2.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "telemetry-incoming-b.r53-2.services.mozilla.com" "${glean}"

## Top Sites
noop_mozilla_endpoints "topsites.services.mozilla.com" "${application_services}"
noop_mozilla_endpoints "topsites.services.mozilla.com" "${mozilla_release}/mobile"
noop_mozilla_endpoints "topsites.services.mozilla.com" "${mozilla_release}/modules"
noop_mozilla_endpoints "topsites.services.mozilla.com" "${mozilla_release}/netwerk"
noop_mozilla_endpoints "topsites.services.mozilla.com" "${mozilla_release}/python"
noop_mozilla_endpoints "topsites.services.mozilla.com" "${mozilla_release}/toolkit"
noop_mozilla_endpoints "topsites.services.mozilla.com" "${glean}"
